FORMAT: 1A
HOST: http://git.agilestacks.com/api/v1

# Git Service API

Git Service has protected HTTP API to provide access to it's functions, such as:

- creating Git repository from template (unpack from an S3 binary blob);
- uploading files to the repository as commits.

Please read [design](https://github.com/agilestacks/git-service/blob/master/README.md) first.


## Repository [/repositories/{repositoryId}]

`repositoryId` format is `<organization>/<template name>-<template id>`. Template `id` is used
by Git SSH and HTTP servers to obtain repository permissions.
SSH key offered by client is used to find matching users. For HTTP protocol Deployment key is
decoded to determine user id. Alternatively HTTP Basic auth username and password is used with
Auth Service to check user login. Then user' teams are traversed to check for (1) template owner
and (2) teams permissions on the template.
URL names are lowercased, non-alphanumeric characters replaced by dashes `-`.

+ Parameters
    + repositoryId: `agilestacks/my-k8s-template-2` (string) - ID of the Repository


### Retrieve Repository content [GET /repositories/{repositoryId}/blob/{path}{?ref}]

Only files can be retrieved. Attempt to retrieve directory will result in 400 Bad Request.

+ Parameters
    + repositoryId: `agilestacks/my-k8s-template-2` (string) - ID of the Repository
    + path: `README` - file path to retrieve
    + ref: `master` - branch, tag, or ref to retrieve from

+ Request

    + Headers

            X-API-Secret: git-api-secret

+ Response 200 (application/octet-stream)

+ Response 400

+ Response 404

+ Response 403


### Retrieve Repository Git Log [GET /repositories/{repositoryId}/log{?ref}]

+ Parameters
    + repositoryId: `agilestacks/my-k8s-template-2` (string) - ID of the Repository
    + ref: `master` - branch, tag, ref, or commit hash to retrieve log of

+ Request

    + Headers

            X-API-Secret: git-api-secret

+ Response 200 (text/plain; charset=utf-8)

    + Body

            commit 4da13d0749c001bc3257381051a22c139fee7751
            Author: Antons Kranga <anton@agilestacks.com>
            Date:   Wed Aug 2 17:36:54 2017 +0300

                Introduced deployment components

            commit b22432beb65acc29d688a6bb12184d12d72b81d8
            Author: Arkadi Shishlov <arkadi.shishlov@gmail.com>
            Date:   Tue Aug 1 17:49:45 2017 +0300

                Design outline

+ Response 400

+ Response 404

+ Response 403


### Retrieve Repository status [GET /repositories/{repositoryId}/status{?ref}]

+ Parameters
    + repositoryId: `agilestacks/my-k8s-template-2` (string) - ID of the Repository
    + ref: `master` - branch, tag, ref, or commit hash to retrieve status of

+ Request

    + Headers

            X-API-Secret: git-api-secret

+ Response 200 (application/json; charset=utf-8)

            {
                "commit": "8d5787cbf266b6d64e12ee5b92aaf2b1cbe95090",
                "ref": "refs/heads/master",
                "date": "2018-10-29T12:27:04+00:00",
                "author": "Automation Hub <hub@agilestacks.io>",
                "subject": "Manifests"
            }

+ Response 400

+ Response 404

+ Response 403

+ Response 409 (application/json; charset=utf-8)

            {
                "error": "Ref <ref> refer to multiple refs ..."
            }


### Create Repository [PUT]

`remote` is optional. If supplied the content of the remote repository became root of the new repo.
`squash` deletes history creating a repository with single initial commit. If supplied the `message`
is used as initial commit message.

`archive` is optional. If supplied the content of the repository is unpacked from the archive, so it
must be a bare git repo at root of the archive. TAR BZIP2 and GZIP archives are supported. BZIP2 by
default if `archive` suffix is not `gz`.

Otherwise an empty repository is initialized.

+ Request (application/json; charset=utf-8)

    + Headers

            X-API-Secret: git-api-secret

    + Body

            {
                "remote": "git@github.com:agilestacks/components.git",
                "ref": "master",
                "squash": false,
                "message": "Initial squash",

                "archive": "s3://agilestacks/blobs/stack-k8s-aws-1.2.5664.tar.bz2"
            }

+ Response 201

+ Response 403

+ Response 400 (application/json; charset=utf-8)

            {
                "error": "Error parse JSON input"
            }

+ Response 500

+ Response 502

+ Response 504


### Upload file [PUT /repositories/{repositoryId}/commit/file/path{?message}{?mode}{?ref}]

Upload a single file and commit to the repository.

+ Parameters
    + repositoryId: `agilestacks/my-k8s-template-2` (string) - ID of the Repository
    + message: `log entry` (string, optional) - Git commit log message
    + mode: `0755` (string, optional) - File mode in octal
    + ref: `master` - branch to add to

+ Request

    + Headers

            X-API-Secret: git-api-secret

    + Body

            file content

+ Response 204

+ Response 404

+ Response 403

+ Response 500

+ Response 502

+ Response 504


### Upload files [POST /repositories/{repositoryId}/commit{?message}{?ref}]

Upload multiple files and commit to the repository.

+ Parameters
    + repositoryId: `agilestacks/my-k8s-template-2` (string) - ID of the Repository
    + message: `log entry` (string, optional) - Git commit log message
    + ref: `master` - branch to add to

+ Request

    + Headers

            X-API-Secret: git-api-secret
            Content-Type: multipart/form-data; boundary="boundary"

    + Body

            --boundary
            Content-Disposition: form-data; name="hub.yaml"; filename="hub.yaml"
            Mode: 0755

            ...
            --boundary
            Content-Disposition: form-data; name="hub-parameters.yaml"; filename="cloud/hub-parameters.yaml"

            ...
            --boundary--

+ Response 204

+ Response 404

+ Response 403

+ Response 500

+ Response 502

+ Response 504


### Add Git subtrees [POST /repositories/{repositoryId}/subtrees{?ref}]

Add multiple Git subtrees to the repository. Subtree `ref` and `squash` are optional.

+ Parameters
    + repositoryId: `agilestacks/my-k8s-template-2` (string) - ID of the Repository
    + ref: `master` - branch to add subtree to

+ Request (application/json; charset=utf-8)

    + Headers

            X-API-Secret: git-api-secret

    + Body

            {
                "subtrees": [
                    {
                        "prefix": "components",
                        "remote": "git@github.com:agilestacks/components.git",
                        "ref": "master",
                        "squash": false
                    }
                ]
            }

+ Response 204

+ Response 404

+ Response 403

+ Response 500

+ Response 502

+ Response 504


### Delete Repository [DELETE]

+ Request

    + Headers

            X-API-Secret: git-api-secret

+ Response 204

+ Response 404

+ Response 403

+ Response 502

+ Response 504
